config/routes.rb
# config/routes.rb
Rails.application.routes.draw do

  root 'cars#index'

  # listados
  get "marca/:brand_name" => "brands#index", as: 'clients_index_by_brand'
  get "anio/:year" => "years#index", as: 'clients_index_by_year'

  # vistas de un auto
  get "promo/:id" => "clients#show", as: 'show_from_home'
  get "marca/:brand_name/auto/:id" => "brands#show", as: 'show_from_brand'
  get "anio/:year/auto/:id" => "years#show", as: 'show_from_year'


  namespace :admin do
    get 'cars/index'
    post 'cars/load'
  end
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id           :bigint           not null, primary key
#  description  :string
#  price        :integer
#  transmission :integer          default("manual"), not null
#  year         :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  model_id     :bigint
#
# Indexes
#
#  index_cars_on_model_id  (model_id)
#
# Foreign Keys
#
#  fk_rails_...  (model_id => models.id)
#
class Car < ApplicationRecord

  enum transmission: { manual: 1, auto: 2, other: 3 }, _prefix: true

  belongs_to :model, inverse_of: :cars
  has_one :brand, through: :model
  has_and_belongs_to_many :stores

  validates :brand, :model, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 5_000_000, less_than: 30_000_000 }

  scope :old, -> { where("year < ?", Date.today.year - 5) }
  scope :most_expensive_first, -> { order(price: :desc) }

  def self.expensive
    # necesito saber cuantos autos hay para saber donde esta el 30% mas caro
    total = Car.all.count
    limit_30_percent_nth = (total * 0.3).to_i # este es el elemento correspondiente al 30%
    limit_30_value = Car
      .order(price: :desc)
      .limit(1)
      .offset(limit_30_percent_nth)
      .pluck(:price)
      .first # este es el 30% mas caro
    # por ultimo, completamos este scope
    where("price >= ?", limit_30_value )
  end

  def self.highlighted
    # un auto es destacado si es anterior a los ultimos 5 años
    # y es del 30% mas caro
    old.expensive
  end

  def brand_name
    brand.name
  end

  def car_model_name
    model.name
  end

  def brand_and_model
    "#{brand_name} #{car_model_name}"
  end

end

app/controllers/admin/cars_controller.rb
module Admin
  class CarsController < BaseController
    def index
      # TODO
    end

    def load
      type = params[:load_type]
      file = params[:file]
      filename = file.original_filename.downcase


      record_storage = case type
      when "brands"
        FileLoaders::BrandStorage.new
      when "models"
        FileLoaders::ModelStorage.new
      when "cars"
        FileLoaders::CarStorage.new
      else
        raise "No implementado"
      end

      file_loader = if filename.end_with?('.csv')
        FileLoaders::CsvFileLoader.new(record_storage)
      elsif filename.end_with?('.xlsx')
        FileLoaders::ExcelFileLoader.new(record_storage)
      elsif filename.end_with?('.json')
        FileLoaders::JsonFileLoader.new(record_storage)
      else
        raise "Formato de archivo desconocido"
      end

      ActiveRecord::Base.transaction do
        # vamos a hacer la carga dentro de una transacción
        file_loader.load file
      end
      redirect_to admin_cars_index_url, notice: "#{type} loaded"
    end
  end
end

app/controllers/cars_controller.rb
# app/controllers/cars_controller.rb

class CarsController < ClientsController
  def index
    # voy a cargar 24 autos destacados (elegidos al azar entre 200)
    cars = Car.highlighted.limit(200).sample(24)
    # finalmente ordenare los autos en grupos de a 6
    @cars_groups = []
    group = []
    cars.each do |car|
      group << car
      if group.length == 6
        @cars_groups << group
        group = []
      end
    end
    if group.length > 0
      @cars_groups << group
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to cars_index_path, notice: 'Auto creado con éxito'
    else
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(:model_id, :price)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/admin/cars/index.html.erb
<div class="container">
  <h1>Administración de autos</h1>

  <div style="background: red; color: #f3f3f3; padding: 1.5rem 1rem; display: flex; justify-content: space-between; align-items: center;">
    <p>Find me in app/views/admin/cars/index.html.erb</p>
    <p style="font-size: 2rem; flex: 1 1 auto; text-align: center; margin: 0;">TODO</p>
  </div>

  <% if notice.present? %>
    <p style="display: block; border: 2px solid green; padding: 5px; margin: 2px;"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p style="display: block; border: 2px solid red; padding: 5px; margin: 2px;"><%= alert %></p>
  <% end %>

  <h2>Carga masiva de autos</h2>
  <%= form_tag(admin_cars_load_path, method: :post, multipart: true) do %>

    <p>Elija que cargar y luego seleccione el archivo a usar (formatos admitidos: csv, xlsx y json)</p>

    <%= select_tag "load_type", options_for_select([
        ["Autos", "cars"],
        ["Modelos", "models"],
        ["Marcas", "brands"]
    ]) %>

    <%= file_field_tag 'file' %>

    <%= submit_tag "Cargar" %>
  <% end %>

</div>