config/routes.rb
# config/routes.rb
Rails.application.routes.draw do

  root 'cars#index'

  # listados
  get "marca/:brand_name" => "brands#index", as: 'clients_index_by_brand'
  get "anio/:year" => "years#index", as: 'clients_index_by_year'

  # vistas de un auto
  get "promo/:id" => "clients#show", as: 'show_from_home'
  get "marca/:brand_name/auto/:id" => "brands#show", as: 'show_from_brand'
  get "anio/:year/auto/:id" => "years#show", as: 'show_from_year'


  namespace :admin do
    get 'cars/index'
    post 'cars/load'
  end
end

app/models/brand.rb
# == Schema Information
#
# Table name: brands
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_brands_on_name  (name) UNIQUE
#
class Brand < ApplicationRecord
  has_many :models, inverse_of: :brand
  has_many :cars, through: :models

  validates :name, uniqueness: true
end

app/controllers/brands_controller.rb
# app/controllers/brands_controller.rb

class BrandsController < ClientsController

  before_action :load_brand

  def index
    @cars = @brand
      .cars
      .eager_load(model: :brand)
      .order("models.name" => :asc, year: :asc, "cars.id" => :asc)

    @cars = paginate(@cars)
  end

  def show
    @car = @brand.cars.find(params[:id])
  end

  protected

  def load_brand
    @brand = Brand.find_by_name(params[:brand_name])
  end
end

app/views/brands/index.html.erb
<%= render 'cars/highlights_top'  %>

<div class="container" id="list">
  <h1><span class="title--light">Los mejores autos de </span> <span class="title--highlight"><%= @brand.name %></span></h1>
  <table class="car-table">
    <thead>
    <tr>
      <th class="car-table__cell car-table__cell--title">Modelo</th>
      <th class="car-table__cell car-table__cell--title">Año</th>
      <th class="car-table__cell car-table__cell--title">Transmición</th>
      <th class="car-table__cell car-table__cell--title">Precio</th>
      <th class="car-table__cell car-table__cell--title"></th>
    </tr>
    </thead>
    <tbody>
    <% @cars.each do |car| %>
      <tr class="car-table__row <%= 'car-table__row--highlight' if @highlights.include?(car) %>">
        <td class="car-table__cell"><%= car.car_model_name %></td>
        <td class="car-table__cell"><%= car.year %></td>
        <td class="car-table__cell"><%= car.transmission_other? ? 'otra' : car.transmission %></td>
        <td class="car-table__cell">
          <%= number_to_currency(car.price, unit: "$", precision: 0, delimiter: ".") %>
          <% if @highlights.include?(car) %>
            <span class="car-table__tag">OFERTA</span>
          <% end %>
        </td>
        <td class="car-table__cell">
          <%= link_to 'Ver detalles', show_from_brand_path(@brand.name,car.id) %>
        </td>
      </tr>
    <% end %>
    </tbody>
    <tfoot>
    <tr>
      <td colspan="5" class="car-table__cell car-table__cell--foot">
        <div class="pagination">
          <% if @page == 1 %>
              <span class="pagination__item pagination__item--disabled">
                <!-- Imagen de FontAwesome - https://fontawesome.com/. Licencia: https://fontawesome.com/license -->
                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="arrow-left" class="svg-inline--fa fa-arrow-left fa-w-14 pagination__icon" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                  <path fill="currentColor" d="M257.5 445.1l-22.2 22.2c-9.4 9.4-24.6 9.4-33.9 0L7 273c-9.4-9.4-9.4-24.6 0-33.9L201.4 44.7c9.4-9.4 24.6-9.4 33.9 0l22.2 22.2c9.5 9.5 9.3 25-.4 34.3L136.6 216H424c13.3 0 24 10.7 24 24v32c0 13.3-10.7 24-24 24H136.6l120.5 114.8c9.8 9.3 10 24.8.4 34.3z"></path>
                </svg>
              </span>
          <% else %>
            <%= link_to clients_index_by_brand_path(@brand.name, page: @page - 1, anchor: 'list'), class: 'pagination__item' do %>
              <!-- Imagen de FontAwesome - https://fontawesome.com/. Licencia: https://fontawesome.com/license -->
              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="arrow-left" class="svg-inline--fa fa-arrow-left fa-w-14 pagination__icon" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="currentColor" d="M257.5 445.1l-22.2 22.2c-9.4 9.4-24.6 9.4-33.9 0L7 273c-9.4-9.4-9.4-24.6 0-33.9L201.4 44.7c9.4-9.4 24.6-9.4 33.9 0l22.2 22.2c9.5 9.5 9.3 25-.4 34.3L136.6 216H424c13.3 0 24 10.7 24 24v32c0 13.3-10.7 24-24 24H136.6l120.5 114.8c9.8 9.3 10 24.8.4 34.3z"></path>
              </svg>
            <% end %>
          <% end %>
          <% if @page > 6 %>
            <%= link_to '1', clients_index_by_brand_path(@brand.name, page: 1, anchor: 'list'), class: 'pagination__item' %>
            <span class="pagination__item pagination__item--separator">...</span>
          <% end %>
          <% ((@page <= 6 ? 1 : @page - 4) .. [@page + 5,@pages].min ).each do |page| %>
            <% if @page == page %>
              <span class="pagination__item pagination__item--current"><%= page %></span>
            <% else %>
              <%= link_to page, clients_index_by_brand_path(@brand.name, page: page, anchor: 'list'), class: "pagination__item" %>
            <% end %>
          <% end %>

          <% if @page == @pages %>
              <span class="pagination__item pagination__item--disabled">
                <!-- Imagen de FontAwesome - https://fontawesome.com/. Licencia: https://fontawesome.com/license -->
                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="arrow-right" class="svg-inline--fa fa-arrow-right fa-w-14 pagination__icon" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                  <path fill="currentColor" d="M190.5 66.9l22.2-22.2c9.4-9.4 24.6-9.4 33.9 0L441 239c9.4 9.4 9.4 24.6 0 33.9L246.6 467.3c-9.4 9.4-24.6 9.4-33.9 0l-22.2-22.2c-9.5-9.5-9.3-25 .4-34.3L311.4 296H24c-13.3 0-24-10.7-24-24v-32c0-13.3 10.7-24 24-24h287.4L190.9 101.2c-9.8-9.3-10-24.8-.4-34.3z"></path>
                </svg>
              </span>
          <% else %>
            <%= link_to clients_index_by_brand_path(@brand.name, page: @page + 1, anchor: 'list'), class: 'pagination__item' do %>
              <!-- Imagen de FontAwesome - https://fontawesome.com/. Licencia: https://fontawesome.com/license -->
              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="arrow-right" class="svg-inline--fa fa-arrow-right fa-w-14 pagination__icon" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path fill="currentColor" d="M190.5 66.9l22.2-22.2c9.4-9.4 24.6-9.4 33.9 0L441 239c9.4 9.4 9.4 24.6 0 33.9L246.6 467.3c-9.4 9.4-24.6 9.4-33.9 0l-22.2-22.2c-9.5-9.5-9.3-25 .4-34.3L311.4 296H24c-13.3 0-24-10.7-24-24v-32c0-13.3 10.7-24 24-24h287.4L190.9 101.2c-9.8-9.3-10-24.8-.4-34.3z"></path>
              </svg>
            <% end %>
          <% end %>
        </div>
      </td>
    </tr>
    </tfoot>
  </table>
</div>

<%= render partial: 'cars/highlights_bottom' %>

app/views/brands/show.html.erb
<%= render 'cars/highlights_top'  %>

<div class="container">
  <div class="title-container title-container--with-btn">
    <h1 class="title">
      <span class="title--light">Los mejores autos de </span> <span class="title--highlight"><%= @brand.name %></span> /
       <span class="title--light"><%= @car.brand_name %> <%= @car.car_model_name %></span> <%= @car.year %> <span class="title--highlight"><%= number_to_currency(@car.price, unit: "$", precision: 0, delimiter: ".") %></span>
    </h1>
    <%= link_to "Volver a #{@brand.name}", clients_index_by_brand_path(@brand.name), class: 'btn-back' %>
  </div>
  <div style="
      min-height: 600px;
      border: 2px solid rgb(229,186,28);
      margin: 1rem;
      background:
          linear-gradient(135deg, #ECEDDC 25%, transparent 25%) -50px 0,
              linear-gradient(225deg, #ECEDDC 25%, transparent 25%) -50px 0,
              linear-gradient(315deg, #ECEDDC 25%, transparent 25%),
              linear-gradient(45deg, #ECEDDC 25%, transparent 25%);
      background-size: 100px 100px;
      background-color: rgba(229,186,28,0.3);
      display: flex;
      justify-content: center;
      align-items: center;
  ">
    Placeholder vista de un auto <strong style="margin: 0 0 0 0.3rem; font-size: 150%;">Normal</strong>, con imágenes, descripción, link de venta, etc

  </div>
</div>

<%= render 'cars/highlights_bottom'  %>