config/routes.rb
# config/routes.rb
Rails.application.routes.draw do

  root 'cars#index'

  # listados
  get "marca/:brand_name" => "brands#index", as: 'clients_index_by_brand'
  get "anio/:year" => "years#index", as: 'clients_index_by_year'

  # vistas de un auto
  get "promo/:id" => "clients#show", as: 'show_from_home'
  get "marca/:brand_name/auto/:id" => "brands#show", as: 'show_from_brand'
  get "anio/:year/auto/:id" => "years#show", as: 'show_from_year'


  namespace :admin do
    get 'cars/index'
    post 'cars/load'
  end
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id           :bigint           not null, primary key
#  description  :string
#  price        :integer
#  transmission :integer          default("manual"), not null
#  year         :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  model_id     :bigint
#
# Indexes
#
#  index_cars_on_model_id  (model_id)
#
# Foreign Keys
#
#  fk_rails_...  (model_id => models.id)
#
class Car < ApplicationRecord

  enum transmission: { manual: 1, auto: 2, other: 3 }, _prefix: true

  belongs_to :model, inverse_of: :cars
  has_one :brand, through: :model
  has_and_belongs_to_many :stores

  validates :brand, :model, :price, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 5_000_000, less_than: 30_000_000 }

  scope :old, -> { where("year < ?", Date.today.year - 5) }
  scope :most_expensive_first, -> { order(price: :desc) }

  def self.expensive
    # necesito saber cuantos autos hay para saber donde esta el 30% mas caro
    total = Car.all.count
    limit_30_percent_nth = (total * 0.3).to_i # este es el elemento correspondiente al 30%
    limit_30_value = Car
      .order(price: :desc)
      .limit(1)
      .offset(limit_30_percent_nth)
      .pluck(:price)
      .first # este es el 30% mas caro
    # por ultimo, completamos este scope
    where("price >= ?", limit_30_value )
  end

  def self.highlighted
    # un auto es destacado si es anterior a los ultimos 5 años
    # y es del 30% mas caro
    old.expensive
  end

  def brand_name
    brand.name
  end

  def car_model_name
    model.name
  end

  def brand_and_model
    "#{brand_name} #{car_model_name}"
  end

end

app/controllers/admin/cars_controller.rb
module Admin
  class CarsController < BaseController
    def index
      # TODO
    end

    def load
      type = params[:load_type]
      file = params[:file]
      filename = file.original_filename.downcase


      record_storage = case type
      when "brands"
        FileLoaders::BrandStorage.new
      when "models"
        FileLoaders::ModelStorage.new
      when "cars"
        FileLoaders::CarStorage.new
      else
        raise "No implementado"
      end

      file_loader = if filename.end_with?('.csv')
        FileLoaders::CsvFileLoader.new(record_storage)
      elsif filename.end_with?('.xlsx')
        FileLoaders::ExcelFileLoader.new(record_storage)
      elsif filename.end_with?('.json')
        FileLoaders::JsonFileLoader.new(record_storage)
      else
        raise "Formato de archivo desconocido"
      end

      ActiveRecord::Base.transaction do
        # vamos a hacer la carga dentro de una transacción
        file_loader.load file
      end
      redirect_to admin_cars_index_url, notice: "#{type} loaded"
    end
  end
end

app/controllers/cars_controller.rb
# app/controllers/cars_controller.rb

class CarsController < ClientsController
  def index
    # voy a cargar 24 autos destacados (elegidos al azar entre 200)
    cars = Car.highlighted.limit(200).sample(24)
    # finalmente ordenare los autos en grupos de a 6
    @cars_groups = []
    group = []
    cars.each do |car|
      group << car
      if group.length == 6
        @cars_groups << group
        group = []
      end
    end
    if group.length > 0
      @cars_groups << group
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)

    if @car.save
      redirect_to cars_index_path, notice: 'Auto creado con éxito'
    else
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(:model_id, :price)
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_highlight.html.erb
<%= link_to show_from_home_path(car.id), class: "card car-card car-card--highlight" do  %>
  <div class="car-card__brand"><%= car.brand_name %></div>
  <div class="car-card__model"><%= car.car_model_name %></div>
  <div class="car-card__year"><%= car.year %></div>
  <div class="car-card__description"><%= car.description %></div>
  <div class="car-card__price"><%= number_to_currency(car.price, unit: "$", precision: 0, delimiter: ".") %></div>
  <div class="car-card__fake-link">Ver detalles</div>
<% end %>

app/views/cars/_highlights_bottom.html.erb
<div class="container container--no-bg">
  <div class="card-list card-list--crop">
    <% @highlights.first(6).last(3).each do |car| %>
      <%= render partial: 'cars/highlight', locals: {car: car} %>
    <% end %>
  </div>
</div>

app/views/cars/_highlights_top.html.erb
<div class="container container--no-bg">
  <div class="card-list card-list--crop">
    <% @highlights.first(3).each do |car| %>
      <%= render partial: 'cars/highlight', locals: {car: car} %>
    <% end %>
  </div>
</div>

app/views/cars/index.html.erb
<% @cars_groups.each_with_index do |cars, index| %>
  <div class="<%= 'alt-bg' if index % 2 == 1 %>">
    <div class="container container--no-bg <%= 'container--no-margin' if index > 0 %>">
      <div class="card-list">
        <% cars.each do |car| %>
          <%= link_to show_from_home_path(car.id), class: "card car-card #{'car-card--highlight' if @highlights.include?(car)}" do  %>
            <div class="car-card__brand"><%= car.brand_name %></div>
            <div class="car-card__model"><%= car.car_model_name %></div>
            <div class="car-card__year"><%= car.year %></div>
            <div class="car-card__description"><%= car.description %></div>
            <div class="car-card__price"><%= number_to_currency(car.price, unit: "$", precision: 0, delimiter: ".") %></div>
            <div class="car-card__fake-link">Ver detalles</div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/new.html.erb
<%# views/cars/new.html.erb %>
<h1>Crear auto</h1>
<% if @car.errors.any? %>
  <div>
    Se encontraron errores:
    <ul>
      <% @car.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model: @car, url: cars_create_path, local: true do |f| %>
  <p>
    <%= f.label :model_id, 'Modelo' %>
    <%= f.grouped_collection_select :model_id,
        Brand.all,
        :models,
        :name,
        :id,
        :name,
        include_blank: false
    %>
  </p>
  <p><%= f.label :price, 'Precio' %>$ <%= f.number_field :price %></p>
  <%= f.submit "Crear auto"  %>
<% end %>

app/views/cars/show.html.erb
<%= render 'cars/highlights_top'  %>

<div class="container">
  <div class="title-container title-container--with-btn">
    <h1 class="title">
      <%= @car.brand_name %> <span class="title--light"><%= @car.car_model_name %></span> <%= @car.year %> <span class="title--highlight"><%= number_to_currency(@car.price, unit: "$", precision: 0, delimiter: ".") %></span>
    </h1>
    <%= link_to 'Volver atrás', root_path, class: 'btn-back' %>
  </div>
  <div style="
      min-height: 600px;
      border: 2px solid #ec173a;
      margin: 1rem;
      background:
          linear-gradient(135deg, #ECEDDC 25%, transparent 25%) -50px 0,
              linear-gradient(225deg, #ECEDDC 25%, transparent 25%) -50px 0,
              linear-gradient(315deg, #ECEDDC 25%, transparent 25%),
              linear-gradient(45deg, #ECEDDC 25%, transparent 25%);
      background-size: 100px 100px;
      background-color: rgba(236,23,58,0.2);
      display: flex;
      justify-content: center;
      align-items: center;
  ">
    Placeholder vista de un auto, con imágenes, descripción, link de venta, etc

  </div>
</div>

<%= render 'cars/highlights_bottom'  %>